import D5.FiniteGoal

/-!
# Axiom audit

This file is part of the default build. During elaboration, Lean prints the
axioms on which representative completed declarations depend. The final
theorem will be added here when it exists.
-/

#print axioms D5.paperComm_eq
#print axioms D5.dimensionSubgroup
#print axioms D5.TaharaArithmetic.equation12
#print axioms D5.TaharaArithmetic.dvd_wijj_mul_B2d
#print axioms D5.gamma_six_le_commutator_dimension_five
#print axioms D5.gamma_five_central_mod_gamma_six
#print axioms D5.paperComm_mul_left_mod_gamma_six
#print axioms D5.paperComm_mul_right_mod_gamma_six
#print axioms D5.paperComm_zpow_zpow_mod_gamma_six
#print axioms D5.paperComm_paperComm_zpow_left_mod_gamma_six
#print axioms D5.hallWitt
#print axioms D5.rotation_main_mod_gamma_five
#print axioms D5.rotation_formula19
#print axioms D5.Tahara.mem_dimensionSubgroup_five_iff
#print axioms D5.Tahara.word_mem_dimensionSubgroup_five
#print axioms D5.Tahara.commutator_representative_formula18
#print axioms D5.Tahara.condition6_multiplicative_of_satisfies
#print axioms D5.Tahara.structuralSecondCoefficient_eq
#print axioms D5.paperComm_zpow_right_hallPetresco
#print axioms D5.paperComm_zpow_left_hallPetresco_weight_two
#print axioms D5.transfer_formula20
#print axioms D5.Tahara.formula20_last_three_vanish
#print axioms D5.Tahara.transfer_formula20_reduced
#print axioms D5.transfer_formula22
#print axioms D5.Tahara.transfer_formula22
#print axioms D5.Tahara.structural_expansion21_local
#print axioms D5.Tahara.structural_expansion21_coordinates
#print axioms D5.Tahara.structural_expansion21_coordinates_zpow
#print axioms D5.orderedProduct_orderedProduct_swap_gammaThree
#print axioms D5.Tahara.strictPairProduct_swap
#print axioms D5.Tahara.structural_expansion21_grouped
#print axioms D5.Tahara.formula21_x2_order_nested_coordinates
#print axioms D5.Tahara.structural_expansion21
#print axioms D5.Tahara.formula23_local
#print axioms D5.Tahara.transfer_formula23
#print axioms D5.Tahara.weight_two_pair_rotation
#print axioms D5.Tahara.weight_two_block_cancels26
#print axioms D5.Tahara.condition13_rearranged
#print axioms D5.Tahara.formula21_third_exponent_condition13
#print axioms D5.Tahara.formula27
#print axioms D5.Tahara.alpha_coordinate_expansion
#print axioms D5.Tahara.alpha_coordinate_expansion_zpow
#print axioms D5.Tahara.formula27_split_alpha_streams
#print axioms D5.Tahara.formula28_u_coordinate_expansion
#print axioms D5.Tahara.formula28_wleft_coordinate_expansion
#print axioms D5.Tahara.formula28_wright_coordinate_expansion
#print axioms D5.Tahara.formula28_wprime_coordinate_expansion
#print axioms D5.Tahara.formula28_all_coordinate_expansions
#print axioms D5.Tahara.formula28_rotate_inner
#print axioms D5.Tahara.formula28_threefold_zpow_left
#print axioms D5.Tahara.formula28_u_ratio_factor
#print axioms D5.Tahara.formula28
#print axioms D5.Tahara.formula19_pair
#print axioms D5.Tahara.formula19_low_main
#print axioms D5.Tahara.formula19_and_20_pair
#print axioms D5.Tahara.formula19_and_20_pair_collected
#print axioms D5.Tahara.formula19_and_20_first_product_collected
#print axioms D5.Tahara.formula19_and_20_first_product_to_formula21
#print axioms D5.Tahara.formula18_after_formula19_to_21
#print axioms D5.Tahara.formula18_second_collected
#print axioms D5.Tahara.formula26_cancels_formula18_second
#print axioms D5.Tahara.formula29_first_six_collected
#print axioms D5.Tahara.formula18_to_formula29_grouped
#print axioms D5.Tahara.formula29
#print axioms D5.Tahara.coordinateProduct_is_gammaTwoPower_mod_gammaThree
#print axioms D5.Tahara.formula32
#print axioms D5.Tahara.formula33
#print axioms D5.Tahara.fourfold_second_gammaTwoPower_vanish
#print axioms D5.Tahara.formula35
#print axioms D5.Tahara.formula36_factor_congruent
#print axioms D5.Tahara.formula36_middle_factor_vanish
#print axioms D5.Tahara.formula36
#print axioms D5.Tahara.formula34_wprime_jacobi
#print axioms D5.Tahara.formula34_w_jacobi
#print axioms D5.Tahara.formula34_w_powered
#print axioms D5.Tahara.formula34_wprime_powered
#print axioms D5.Tahara.formula34_wprime_stream
#print axioms D5.Tahara.formula34_w_canonical_product
#print axioms D5.Tahara.tripleProduct_reindex_jik
#print axioms D5.Tahara.tripleProduct_reindex_kij
#print axioms D5.Tahara.formula34_lines_nine_ten_twelve_to_canonical
#print axioms D5.Tahara.formula34_w_streams
#print axioms D5.Tahara.formula35_factor_expanded
#print axioms D5.Tahara.formula35_expanded_product_vanish
#print axioms D5.Tahara.formula35_reindexed_vanish
#print axioms D5.Tahara.formula35_yields_wdoubleprime_main
#print axioms D5.Tahara.formula34WExtraProduct_split_diagonal
#print axioms D5.Tahara.formula29_line_seven_to_formula32_firstLayer
#print axioms D5.Tahara.formula36_yields_wdoubleprime_diagonal_main
#print axioms D5.Tahara.formula34_transformed_streams
#print axioms D5.Tahara.formula34
#print axioms D5.Tahara.formula37
#print axioms D5.Tahara.formula38
#print axioms D5.Tahara.formula39_expand
#print axioms D5.Tahara.formula39
#print axioms D5.Tahara.formula39_strictTripleProduct_vanish
#print axioms D5.Tahara.formula39_strict_principal_streams_vanish
#print axioms D5.Tahara.formula34WMainFactor_diagonal_eq_one
#print axioms D5.Tahara.formula40
#print axioms D5.Tahara.formula41
#print axioms D5.Tahara.formula42
#print axioms D5.Tahara.formula43
#print axioms D5.Tahara.formula44
#print axioms D5.Tahara.formula45
#print axioms D5.Tahara.formula45_first_exponent_identity
#print axioms D5.Tahara.formula45_second_exponent_identity
#print axioms D5.Tahara.formula45_to_formula46_pair
#print axioms D5.Tahara.formula46
#print axioms D5.Tahara.formula34_principal_to_pair_faces
#print axioms D5.Tahara.formula29_to_formula45_source
#print axioms D5.Tahara.formula29_to_formula46
#print axioms D5.Tahara.section13_finite
#print axioms D5.Tahara.formula47
#print axioms D5.Tahara.formula48
#print axioms D5.Tahara.formula49
#print axioms D5.Tahara.paperComm_zpow_left_hallPetresco_mod_gamma_four
#print axioms D5.Tahara.formula50
#print axioms D5.Tahara.formula51
#print axioms D5.Tahara.formula52
#print axioms D5.Tahara.formula53
#print axioms D5.Tahara.formula46_first_two_vanish
#print axioms D5.Tahara.formula54
#print axioms D5.Tahara.formula55_factor_mem_gamma5
#print axioms D5.Tahara.kappa_mem_gamma5
#print axioms D5.Tahara.formula54_kappa
#print axioms D5.Tahara.formula56_mul_left
#print axioms D5.Tahara.formula56_mul_right
#print axioms D5.Tahara.formula56_zpow
#print axioms D5.Tahara.formula56_replace_left
#print axioms D5.Tahara.formula56_replace_right
#print axioms D5.Tahara.formula56_gammaFour_commute
#print axioms D5.Tahara.formula57
#print axioms D5.Tahara.formula58
#print axioms D5.Tahara.formula59_pair
#print axioms D5.Tahara.formula59
#print axioms D5.Tahara.formula59_second_product_vanish
#print axioms D5.Tahara.formula60
#print axioms D5.Tahara.formula61
#print axioms D5.Tahara.formula63_high_exponent
#print axioms D5.Tahara.formula63_low_exponent
#print axioms D5.Tahara.formula63_corrections_vanish
#print axioms D5.Tahara.formula57_rearranged_zpow
#print axioms D5.Tahara.formula62_high_expand
#print axioms D5.Tahara.formula62_low_expand
#print axioms D5.Tahara.formula62_inner_expand
#print axioms D5.Tahara.formula63
#print axioms D5.Tahara.formula62
#print axioms D5.Tahara.Context.x3_coordinate_dvd_of_product_mem
#print axioms D5.Tahara.formula64
#print axioms D5.Tahara.formula65
#print axioms D5.Tahara.formula66_lambda
#print axioms D5.Tahara.formula66_eta
#print axioms D5.Tahara.formula67
#print axioms D5.Tahara.formula68
#print axioms D5.Tahara.formula68_mem_gamma3
#print axioms D5.Tahara.formula69
#print axioms D5.Tahara.sum_product_reindex
#print axioms D5.Tahara.sum_square_partition
#print axioms D5.Tahara.formula70_expansion
#print axioms D5.Tahara.formula70
#print axioms D5.Tahara.formula71_expansion
#print axioms D5.Tahara.formula71
#print axioms D5.Tahara.sum_filter_le_eq_sum_filter_lt_add
#print axioms D5.Tahara.formula72
#print axioms D5.Tahara.formula73
#print axioms D5.Tahara.formula74_expansion
#print axioms D5.Tahara.formula74
#print axioms D5.Tahara.formula74_coordinates
#print axioms D5.Tahara.x3Coordinate_modEq_dvd
#print axioms D5.Tahara.formula75
#print axioms D5.Tahara.formula75_weighted_dvd
#print axioms D5.Tahara.sum_lower_reindex
#print axioms D5.Tahara.formula76_expansion
#print axioms D5.Tahara.formula76
#print axioms D5.Tahara.formula77_expansion
#print axioms D5.Tahara.formula77
#print axioms D5.Tahara.formula78_expansion
#print axioms D5.Tahara.formula78_pair_coefficient_dvd
#print axioms D5.Tahara.formula78_last_dvd
#print axioms D5.Tahara.formula78
#print axioms D5.Tahara.formula79_expansion
#print axioms D5.Tahara.formula79_last_dvd
#print axioms D5.Tahara.formula79
#print axioms D5.Background.gammaTwoFourBasis_exists
#print axioms D5.Tahara.GammaTwoFourBasis.formula80_finite
#print axioms D5.Tahara.GammaTwoFourBasis.formula80
#print axioms D5.Tahara.GammaTwoFourBasis.coordinate_dvd_of_product_mem
#print axioms D5.Tahara.formula81_first
#print axioms D5.Tahara.formula81_second
#print axioms D5.Tahara.formula82
#print axioms D5.Tahara.formula83
#print axioms D5.Tahara.formula84_coordinates
#print axioms D5.Tahara.formula84
#print axioms D5.Tahara.paperComm_coordinateProducts
#print axioms D5.Tahara.paperComm_coordinateProducts_zpow
#print axioms D5.Tahara.strictPairProduct_coordinateSquares_collect
#print axioms D5.Tahara.formula85_first
#print axioms D5.Tahara.formula85_second
#print axioms D5.Tahara.formula85_square_to_pairs
#print axioms D5.Tahara.formula85
#print axioms D5.Tahara.formula86
#print axioms D5.Tahara.formula87_start
#print axioms D5.Tahara.formula87_first_difference
#print axioms D5.Tahara.formula87_first_congruence
#print axioms D5.Tahara.formula87_second_difference
#print axioms D5.Tahara.formula87_second_congruence
#print axioms D5.Tahara.formula87
#print axioms D5.finite_group_theorem_of_nilpotent_elementwise
